name: Upload Jar
on: workflow_dispatch
jobs:
  build:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    
    - name: Running gradle build
      run: gradle build

    - name: Uploading Jar and Files
      uses: actions/upload-artifact@v2
      with:
        name: All
        path: |
            androidide-jdk-transform/build
            
  
